apiVersion: notification-ctrlr.netop-types.io/v1alpha1
kind: Notification
metadata:
  creationTimestamp: null
  name: ocpgf1-netop-manager-system-netop-manager-controller-manager-dockercfg-rq6l5-secret-core-v1
spec:
  clusterName: ocpgf1
  objRef:
    apiVersion: v1
    kind: Secret
    name: netop-manager-controller-manager-dockercfg-rq6l5
    namespace: netop-manager-system
  serializedObj: '{"kind":"Secret","apiVersion":"v1","metadata":{"name":"netop-manager-controller-manager-dockercfg-rq6l5","namespace":"netop-manager-system","creationTimestamp":null},"data":{".dockercfg":"e30="},"type":"kubernetes.io/dockercfg"}'
status:
  state: ""
