apiVersion: notification-ctrlr.netop-types.io/v1alpha1
kind: Notification
metadata:
  creationTimestamp: null
  name: ocpgf1-aci-containers-system-builder-dockercfg-6g4fr-secret-core-v1
spec:
  clusterName: ocpgf1
  objRef:
    apiVersion: v1
    kind: Secret
    name: builder-dockercfg-6g4fr
    namespace: aci-containers-system
  serializedObj: '{"kind":"Secret","apiVersion":"v1","metadata":{"name":"builder-dockercfg-6g4fr","namespace":"aci-containers-system","creationTimestamp":null},"data":{".dockercfg":"e30="},"type":"kubernetes.io/dockercfg"}'
status:
  state: ""
