apiVersion: notification-ctrlr.netop-types.io/v1alpha1
kind: Notification
metadata:
  creationTimestamp: null
  name: ocpgf1-netop-manager-system-netop-manager-cni-config-configmap-core-v1
spec:
  clusterName: ocpgf1
  objRef:
    apiVersion: v1
    kind: ConfigMap
    name: netop-manager-cni-config
    namespace: netop-manager-system
  serializedObj: '{"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"netop-manager-cni-config","namespace":"netop-manager-system","creationTimestamp":null},"data":{"cniconfig.yaml":"cniConfig:\n  cko-cni-calico:\n  -
    \"01-calico.conflist\"\n  - \"01-calico.conf\"\n  - \"10-calico.conflist\"\n  -
    \"10-calico.conf\"\n  cko-cni-aci:\n  - \"01-opflex-cni.conf\"\n  - \"10-opflex-cni.conf\"\n  cko-cni-cilium:\n  -
    \"05-cilium.conf\"\n  cko-cni-awsvpc:\n  - \"10-aws.conflist\"\n  - \"10-aws.conf\""}}'
status:
  state: ""
