apiVersion: notification-ctrlr.netop-types.io/v1alpha1
kind: Notification
metadata:
  creationTimestamp: null
  name: ocpgf1-netop-manager-system-netop-manager-manager-config-configmap-core-v1
spec:
  clusterName: ocpgf1
  objRef:
    apiVersion: v1
    kind: ConfigMap
    name: netop-manager-manager-config
    namespace: netop-manager-system
  serializedObj: '{"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"netop-manager-manager-config","namespace":"netop-manager-system","creationTimestamp":null},"data":{"controller_manager_config.yaml":"apiVersion:
    controller-runtime.sigs.k8s.io/v1alpha1\nkind: ControllerManagerConfig\nhealth:\n  healthProbeBindAddress:
    :8081\nmetrics:\n  bindAddress: 127.0.0.1:9999\nwebhook:\n  port: 9443\nleaderElection:\n  leaderElect:
    true\n  resourceName: 51681485.netop-manager.io\n# leaderElectionReleaseOnCancel:
    true\n"}}'
status:
  state: ""
